

<?php
if (strcmp($function, "salin") == 0) {
	// echo $id."|".$description."|".$libur."|".$gilir."|".$lintas_hari_masuk."|".$dws_start_time."|".$istirahat."|".$lintas_hari_mulai_istirahat."|".$dws_break_start_time."|".$lintas_hari_akhir_istirahat."|".$dws_break_end_time."|".$lintas_hari_pulang."|".$dws_end_time."|".$dws."|".$dws_variant."|".$status;
} else if (strcmp($function, "ubah") == 0) {
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>No Pokok</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='aksi' value='ubah'/>";
	echo "<input class='form-control' type='hidden' name='id_pengajuan_lembur' value='$id'/>";
	echo "<input class='form-control get_approver' type='hidden' value='$np_approver'>";
	echo "<input class='form-control no_pokok' id='no_pokok' type='text' name='no_pokok_ubah' onChange='getNama()' value='$no_pokok' placeholder='No Pokok' disabled>";
	echo "</div>";
	echo "<div id='warning_no_pokok_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Nama Pegawai</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' id='nama_pegawai' value='$nama_pegawai' placeholder='Nama Pegawai' disabled>";
	echo "</div>";
	echo "<div id='warning_nama_pegawai_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Tertanggal</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='tgl_dws' value='$tgl_dws' placeholder='Tertanggal' >";
	echo "<input class='form-control tgl_dws' type='date' name='tgl_dws_ubah' value='$tgl_dws' placeholder='Tertanggal'>";
	echo "</div>";
	echo "<div id='warning_tgl_dws_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Tanggal Mulai</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='tgl_mulai' value='$tgl_mulai' placeholder='Tanggal Mulai' >";
	echo "<input class='form-control tgl_mulai' type='date' name='tgl_mulai_ubah' value='$tgl_mulai' placeholder='Tanggal Mulai' onChange='getWaktu()'>";
	echo "</div>";
	echo "<div id='warning_tgl_mulai_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Jam Mulai</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='jam_mulai' value='$jam_mulai' placeholder='Jam Mulai' >";
	echo "<input class='form-control jam_mulai' type='time' name='jam_mulai_ubah' value='$jam_mulai' placeholder='Jam Mulai' onChange='getWaktu()'>";
	echo "</div>";
	echo "<div id='warning_jam_mulai_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Tanggal Selesai</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='tgl_selesai' value='$tgl_selesai' placeholder='Tanggal Selesai' >";
	echo "<input class='form-control tgl_selesai' type='date' name='tgl_selesai_ubah' value='$tgl_selesai' placeholder='Tanggal Selesai' onChange='getWaktu()'>";
	echo "</div>";
	echo "<div id='warning_tgl_selesai_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Jam Selesai</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='jam_selesai' value='$jam_selesai' placeholder='Jam Selesai' >";
	echo "<input class='form-control jam_selesai' type='time' name='jam_selesai_ubah' value='$jam_selesai' placeholder='Jam Selesai' onChange='getWaktu()'>";
	echo "</div>";
	echo "<div id='warning_jam_selesai_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Total Jam</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<label class='set_jam' id='set_jam'>$jam_diakui</label>";
	echo "</div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>NP Approver</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='np_approver' value='$np_approver' placeholder='NP Approver'>";
	echo "<select class='form-control select2 set_approval_select' id='np_approver' name='np_approver_ubah' required>
					$daftar_approval
					</select>";
	// <input class='form-control np_approver' id='np_approver' type='text' name='np_approver_ubah' onChange='getNamaApv()' value='$np_approver' placeholder='NP Approver'>";
	echo "</div>";
	echo "<div id='warning_np_approver_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	/*echo "<div class='row'>";
			echo "<div class='form-group'>";
				echo "<div class='col-lg-4'>";
					echo "<label>NP Approver</label>";
				echo "</div>";
				echo "<div class='col-lg-8'>";
					echo "<input class='form-control' type='hidden' name='np_approver' value='$np_approver' placeholder='NP Approver'>";
					echo "<input class='form-control np_approver' id='np_approver' type='text' name='np_approver_ubah' onChange='getNamaApv()' value='$np_approver' placeholder='NP Approver' disabled>";
				echo "</div>";
				echo "<div id='warning_np_approver_ubah' class='col-lg-3 text-danger'></div>";
			echo "</div>";
		echo "</div>";
		echo "<div class='row'>";
			echo "<div class='form-group'>";
				echo "<div class='col-lg-4'>";
					echo "<label>Nama Approver</label>";
				echo "</div>";
				echo "<div class='col-lg-8'>";
					echo "<input class='form-control' id='nama_approver' value='$nama_approver' placeholder='Nama Approver' disabled>";
				echo "</div>";
				echo "<div id='warning_nama_approver_ubah' class='col-lg-3 text-danger'></div>";
			echo "</div>";
		echo "</div>";*/ //tidak dipakai
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Jenis Alasan</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='alasan' value='$alasan' placeholder='NP Approver'>";
	echo "<select class='form-control select2 set_alasan_select' id='alasan' name='alasan_ubah' required>
					$kategori_lembur
					</select>";
	// <input class='form-control np_approver' id='np_approver' type='text' name='np_approver_ubah' onChange='getNamaApv()' value='$np_approver' placeholder='NP Approver'>";
	echo "</div>";
	echo "<div id='warning_alasan_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
	echo "<div class='row'>";
	echo "<div class='form-group'>";
	echo "<div class='col-lg-4'>";
	echo "<label>Keterangan</label>";
	echo "</div>";
	echo "<div class='col-lg-8'>";
	echo "<input class='form-control' type='hidden' name='keterangan' value='$keterangan' placeholder='Keterangan'>";
	echo "<input class='form-control' type='text' name='keterangan_ubah' id='keterangan' value='$keterangan' placeholder='Keterangan'>";
	echo "</div>";
	echo "<div id='warning_keterangan_ubah' class='col-lg-3 text-danger'></div>";
	echo "</div>";
	echo "</div>";
} ?>
		